name: Cleanup Terminated Terraform runs

on:
  push:
    paths:
      - .github/workflows/terraform-cleanup-pipeline.yaml
    branches:
      - pipeline-cleanup

env:
  TF_WORKING_DIR: ./terraform

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Force unlock Terraform state
        run: terraform force-unlock -force 1779693167235828